name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Access KAKAO_SDK_APPKEY
      run: echo '${{ secrets.KAKAO_SDK_APPKEY}}' > local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: 의존성 라이브러리 다운로드 및 확인
      run: ./gradlew androidDependencies
      
    - name: 프로젝트 빌드
      run: ./gradlew assembleDebug
