name: Android CI

on:
  pull:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: 의존성 라이브러리 다운로드 및 확인
      run: ./gradlew androidDependencies
      
    - name: 프로젝트 빌드
      run: ./gradlew assembleDebug
    # 코틀린 코드 스타일 체크
    # reporter
    #  - github-pr-review : 댓글로 리뷰 추가
    #  - github-pr-check  : Annotation으로 추가
    # android             : Android Kotlin Code Style도 함께 체크할 것인지
    # fail_on_error       : 오류가 발생되면 실패로 처리할 것인지
    # level               : Lint 레벨
    
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
      
    steps:
      - name: 리포지터리 클론
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          
      - name: 코틀린 코드 스타일 체크
        uses: ScaCap/action-ktlint@master
        with:
          github_token: $
          reporter: github-pr-review 
          android: true
          fail_on_error: true
          level: warning