name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Generate Keystore File
    - name: Generate Keystore File
      run : |
        echo "${{ secrets.APP_KEYSTORE_BASE64}}" > ./keystore.b64
        base64 -d -i ./keystore.b64 > ./Smiley.jks
      env:
        KEYSTORE: ${{ secrets.APP_KEYSTORE_BASE64 }}

    # Generate keystore.properties
    - name: Generate keystore.properties
      run: |
        echo storePassword=${{ secrets.STORE_PASSWORD }} > ./keystore.properties
        echo keyPassword=${{ secrets.KEY_PASSWORD }} >> ./keystore.properties
        echo keyAlias=${{ secrets.KEY_ALIAS }} >> ./keystore.properties
        echo storeFile=${{ secrets.STORE_FILE }} >> ./keystore.properties
        echo ./keystore.properties

    - name: Access KAKAO_SDK_APPKEY
      env:
        APOD_API_KEY: ${{ secrets.KAKAO_SDK_APPKEY }}
      run: echo KAKAO_SDK_APPKEY=\"$KAKAO_SDK_APPKEY\" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: 의존성 라이브러리 다운로드 및 확인
      run: ./gradlew androidDependencies
      
    - name: 프로젝트 빌드
      run: ./gradlew assembleDebug
