name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    # Generate Keystore File
    - name: Generate Keystore File
      env:
        KEY_STORE: ${{ secrets.APP_KEYSTORE_BASE64 }}
      run : |
        echo $KEY_STORE > ./keystore.b64
        base64 -d -i ./keystore.b64 > ./Smiley.jks


    # Generate keystore.properties
    - name: Generate keystore.properties
      env:
        STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        STORE_FILE: ${{ secrets.STORE_FILE }}
      run: |
        echo storePassword=$STORE_PASSWORD > ./keystore.properties
        echo keyPassword=$KEY_PASSWORD >> ./keystore.properties
        echo keyAlias=$KEY_ALIAS >> ./keystore.properties
        echo storeFile=../$STORE_FILE >> ./keystore.properties

    # Kakao App Key
    - name: Access KAKAO_SDK_APPKEY
      env:
        KAKAO_SDK_APPKEY: ${{ secrets.KAKAO_SDK_APPKEY }}
      run: |
        echo KAKAO_SDK_APPKEY=\"$KAKAO_SDK_APPKEY\" > ./local.properties
        cat ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: 의존성 라이브러리 다운로드 및 확인
      run: ./gradlew androidDependencies
      
    - name: 프로젝트 빌드
      run: ./gradlew assembleDebug
