name: Create Debug APK

on:
  push:
    branches: [ "develop" ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Kakao App Key
      - name: Access KAKAO_SDK_APPKEY
        env:
          APOD_API_KEY: ${{ secrets.KAKAO_SDK_APPKEY }}
        run: echo KAKAO_SDK_APPKEY=\"$KAKAO_SDK_APPKEY\" > ./local.properties

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: presentation/build/outputs/apk/debug