name: Auto Release (Main)
on:
  push:
    branches: [ "main" ]
    
jobs:
  # Release APK 생성
  apk:
    permissions: write-all
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # merge commit에서 release 버전 정보 추출
      - name: 버전 정보 추출
        id: extract_version_name
        run: echo "##[set-output name=version;]$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"

      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          replacename: true
          name: Smiley v'${{ steps.extract_version_name.outputs.version }}' - official
          replacebody: true
          body: |
            ## Smiley v${{ steps.extract_version_name.outputs.version }} 정식 버전이 릴리즈 되었습니다.
            - Apk 다운로드 -> [Apk Downloads](https://github.com/DEU-Smiley/Smiley-Android-App/releases/download/${{ steps.extract_version_name.outputs.version }}/app-release.apk) 
            - Apk는 위의 링크 또는 해당 게시글 하단에서 다운로드 받을 수 있습니다.
            - 만약 해당 게시글에 Apk 파일이 업로드 되어 있지 않다면 아래 절차를 통해 다운로드 받아주세요.


            ### Apk 다운로드
            1. [Apk Downloads](https://github.com/DEU-Smiley/Smiley-Android-App/actions/workflows/auto_release.yml?query=is%3Asuccess+) 로 이동하세요.
            2. 목록 중 가장 최근에 완료된 항목(초록색 체크 표시)을 클릭하세요.
            3. Artifacts 탭에서 apk 파일을 다운로드 할 수 있습니다.
