# 코틀린 코드 스타일 체크
# reporter
#  - github-pr-review : 댓글로 리뷰 추가
#  - github-pr-check  : Annotation으로 추가
# android             : Android Kotlin Code Style도 함께 체크할 것인지
# fail_on_error       : 오류가 발생되면 실패로 처리할 것인지
# level               : Lint 레벨

name: reviewdog
on: [pull_request]    

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
      
    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1
          
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: $ {{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review 
          android: true
          fail_on_error: true
          level: warning